name: CloudFormation Deployment

on:
  workflow_run:
    workflows: ["Java CI with Maven Build and S3 Deployment"]
    types:
      - completed


jobs:
  deploy-cf-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
         name: my-stack
         template: https://cfdeployment.s3.ap-southeast-2.amazonaws.com/Instanceparam.json
         capabilities: CAPABILITY_NAMED_IAM
         parameter-overrides: |
           ArtifactBucket=devtest-deployment
           ArtifactKey="https://devtest-deployment.s3.ap-southeast-2.amazonaws.com/maven-artifacts.jar"
           InstanceType=t2.micro
           KeyNameParam=${{ secrets.SSH_PRIVATE_KEY }}
