name: Java CI with Maven Build and S3 Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Review-code-and-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
   
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Upload Maven artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maven-artifacts
          path: target
          
      - name: Download Maven artifacts
        uses: actions/download-artifact@v2
        with:
          name: maven-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: List contents of the directory
        run: ls -R

      - name: Upload artifact to S3
        run:   aws s3 cp ./target/mb2g-spring-boot-0.0.1-SNAPSHOT.jar s3://devtest-deployment/maven-artifacts.jar

      - name: Upload CF Script to S3
        run: aws s3 cp ./cicd/Instanceparam.json s3://cfdeployment/

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
