name: Java CI with Maven Build and S3 Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Review-code-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
   
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Maven artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maven-artifacts
          path: target

  Deploy-to-S3:
    needs: Review-code-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Download Maven artifacts
        uses: actions/download-artifact@v2
        with:
          name: maven-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: List contents of the directory
        run: ls -R /home/runner/work/spring-simple-maven/spring-simple-maven/cicd/

      - name: Upload artifact to S3
        run: aws s3 cp /home/runner/work/spring-simple-maven/spring-simple-maven/mb2g-spring-boot-0.0.1-SNAPSHOT.jar s3://devtest-deployment/maven-artifacts.jar

      - name: Upload CF Script to S3
        run: aws s3 cp /home/runner/work/spring-simple-maven/spring-simple-maven/cicd/Instanceparam.json s3://cfdeployment/
               
  Deploy-to-EC2:
    needs: Deploy-to-S3
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     
      - name: SSH into EC2 instance and copy artifact
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy.pem
          chmod 600 deploy.pem
          ssh -o StrictHostKeyChecking=no -i deploy.pem ec2-user@ec2-54-66-248-163.ap-southeast-2.compute.amazonaws.com 'aws s3 cp s3://devtest-deployment/maven-artifacts.jar /home/ec2-user/deploy/'
