name: Java CI with Maven Build and S3 Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Review-code-and-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
   
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Upload Maven artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maven-artifacts
          path: target
          
      - name: Download Maven artifacts
        uses: actions/download-artifact@v2
        with:
          name: maven-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: List contents of the directory
        run: ls -R 

   #   - name: Upload artifact to S3
    #    run: aws s3 cp ./target/mb2g-spring-boot-0.0.1-SNASHOT.jar s3://devtest-deployment/maven-artifacts.jar

    #  - name: Upload CF Script to S3
     #   run: aws s3 cp ./cicd/Instanceparam.json s3://cfdeployment/
  Review-PR:
     runs-on: ubuntu-latest
     needs: Review-code-and-build
     if: github.event_name == 'pull_request'
     steps:
      - name: Check if unit tests passed
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Unit tests passed, approving PR."
            # Approve PR
            gh pr review --approve
          else
            echo "Unit tests failed, stopping PR."
            # Stop PR
            gh pr review --reject
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
